In [55]:
import numpy as np
from numpy import loadtxt
from io import StringIO 

In [56]:
#The dataset has 506 samples with 14 attributes

In [57]:
phi = np.loadtxt('train.csv', dtype='float', delimiter=',', skiprows=1,usecols=tuple(range(1, 14)))

phi_test = np.loadtxt('test.csv', dtype='float', delimiter=',',skiprows=1, usecols=tuple(range(1, 14)))

In [58]:
phi

array([[9.55770e-01, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.06380e+02, 1.72800e+01],
       [2.87500e-02, 2.80000e+01, 1.50400e+01, ..., 1.82000e+01,
        3.96330e+02, 6.21000e+00],
       [1.22358e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        3.63430e+02, 4.59000e+00],
       ...,
       [6.65492e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96900e+02, 1.39900e+01],
       [1.31170e-01, 0.00000e+00, 8.56000e+00, ..., 2.09000e+01,
        3.87690e+02, 1.40900e+01],
       [6.46600e-02, 7.00000e+01, 2.24000e+00, ..., 1.48000e+01,
        3.68240e+02, 4.97000e+00]])

In [59]:
y = np.loadtxt('train.csv', dtype='float', delimiter=',', skiprows=1,usecols=14, ndmin=2)

In [60]:
#Concatenate coloumn of 1s to right of phi and phi_test
phi=np.concatenate((phi, np.ones((400, 1))), axis=1)

phi_test= np.concatenate((phi_test, np.ones((105, 1))), axis=1)


In [61]:
phi.shape

(400, 14)

In [62]:
phi

array([[9.55770e-01, 0.00000e+00, 8.14000e+00, ..., 3.06380e+02,
        1.72800e+01, 1.00000e+00],
       [2.87500e-02, 2.80000e+01, 1.50400e+01, ..., 3.96330e+02,
        6.21000e+00, 1.00000e+00],
       [1.22358e+00, 0.00000e+00, 1.95800e+01, ..., 3.63430e+02,
        4.59000e+00, 1.00000e+00],
       ...,
       [6.65492e+00, 0.00000e+00, 1.81000e+01, ..., 3.96900e+02,
        1.39900e+01, 1.00000e+00],
       [1.31170e-01, 0.00000e+00, 8.56000e+00, ..., 3.87690e+02,
        1.40900e+01, 1.00000e+00],
       [6.46600e-02, 7.00000e+01, 2.24000e+00, ..., 3.68240e+02,
        4.97000e+00, 1.00000e+00]])

In [63]:
#Scaling phi and phi_test for given range(0,1)

for i in range(0, 13):
    maximum= max(phi[:, i])
    minimum= min(phi[:, i])
    phi[:, i]= (phi[:, i] - minimum) / (maximum - minimum)
    phi_test[:, i]= (phi_test[:, i] -minimum) / (maximum - minimum)


In [64]:
phi

array([[1.06411199e-02, 0.00000000e+00, 2.81524927e-01, ...,
        7.71748449e-01, 4.26074896e-01, 1.00000000e+00],
       [2.21317669e-04, 2.94736842e-01, 5.34457478e-01, ...,
        9.98562711e-01, 1.19001387e-01, 1.00000000e+00],
       [1.36513324e-02, 0.00000000e+00, 7.00879765e-01, ...,
        9.15603409e-01, 7.40638003e-02, 1.00000000e+00],
       ...,
       [7.47001646e-02, 0.00000000e+00, 6.46627566e-01, ...,
        1.00000000e+00, 3.34812760e-01, 1.00000000e+00],
       [1.37252923e-03, 0.00000000e+00, 2.96920821e-01, ...,
        9.76776439e-01, 3.37586685e-01, 1.00000000e+00],
       [6.24949841e-04, 7.36842105e-01, 6.52492669e-02, ...,
        9.27732110e-01, 8.46047157e-02, 1.00000000e+00]])

In [65]:
#Apply log scaling on y

y=np.log(y)

In [66]:
y=np.ravel(y)

In [67]:
y.shape

(400,)

In [68]:
from sklearn.linear_model import SGDRegressor,Lasso,Ridge

In [69]:
sgd=SGDRegressor()
sgd.fit(phi,y)

SGDRegressor()

In [70]:
sgd.coef_

array([-0.11038809,  0.25056119, -0.00225683,  0.14676508,  0.0139097 ,
        0.6824259 ,  0.19273294,  0.3184194 , -0.12653571, -0.11695907,
        0.14818076,  0.77225007, -0.18975202,  0.90070473])

In [71]:
sgd.intercept_

array([0.90154031])

In [72]:
sgd.score(phi,y)

0.4833373963622031

In [76]:
lasso=Lasso(alpha=0.2)
lasso.fit(phi,y)


Lasso(alpha=0.2)

In [77]:
lasso.score(phi,y)

0.0

In [75]:
ridge=Ridge()
ridge.fit(phi,y)
ridge.score(phi,y)

0.7890307008586942